{
 "title": "Poller",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(go_memstats_alloc_bytes,job)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "pod",
    "query": "label_values(go_memstats_alloc_bytes{job=\"$job\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Valid Votes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(poller_valid_votes{job=\"$job\"}) / sum(poller_total_votes{job=\"$job\"}) * 100"
    }
   ]
  },
  {
   "title": "Invalid Votes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(poller_invalid_votes) / sum(poller_total_votes) * 100"
    }
   ]
  },
  {
   "title": "Retried Votes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(poller_retried_votes{job=\"$job\"}) / sum(poller_total_votes{job=\"$job\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Votes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(poller_total_votes{job=\"$job\"})",
     "legendFormat": "Total Votes"
    }
   ]
  },
  {
   "title": "Total  Valid Votes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(poller_valid_votes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Total Invalid Votes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(poller_invalid_votes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Total Retried Votes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(poller_retried_votes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Votes - $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "repeat": "pod",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "poller_total_votes{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "Total Votes"
    }
   ]
  },
  {
   "title": "Valid Votes - $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "repeat": "pod",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "poller_valid_votes{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "Valid Votes"
    }
   ]
  },
  {
   "title": "Retried Votes - $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "repeat": "pod",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "poller_retried_votes{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "Retried Votes"
    }
   ]
  },
  {
   "title": "Invalid Votes - $pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "repeat": "pod",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "poller_invalid_votes{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "Invalid Votes"
    }
   ]
  },
  {
   "title": "go memstats - $pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "repeat": "pod",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "bytes allocated "
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\",pod=\"$pod\"}[30s])",
     "legendFormat": "alloc rate "
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "stack inuse "
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "heap inuse "
    }
   ]
  },
  {
   "title": "go memstats deriv - $pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
   "repeat": "pod",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{job=\"$job\",pod=\"$pod\"}[$interval])",
     "legendFormat": "bytes allocated -"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\",pod=\"$pod\"}[$interval])",
     "legendFormat": "alloc rate "
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{job=\"$job\",pod=\"$pod\"}[$interval])",
     "legendFormat": "stack inuse "
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{job=\"$job\",pod=\"$pod\"}[$interval])",
     "legendFormat": "heap inuse "
    }
   ]
  },
  {
   "title": "GC duration quantiles - $pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "repeat": "pod",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "{{quantile}} "
    }
   ]
  },
  {
   "title": "Goroutines-$pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
   "repeat": "pod",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\",pod=\"$pod\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}